// <auto-generated />
namespace Development.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ClassTests : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ClassTests));
        
        string IMigrationMetadata.Id
        {
            get { return "201702132219559_ClassTests"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
